### ISSUE TITLE
Managing added files

### ISSUE THREAD

**Issue by adrianborkowski** [torre76/django-googledrive-storage#18]
Is there any possibility to manage added files by this app? E.g. get url of added image to use it in django template?

**Comment by torre76** [comment]
Yes, it is possible and, if you try the package and check the result you acquire from Google Drive, you can easily find the link you are looking for.

Please bear in mind that issues is used to **track defect** of the package, not for asking help about how to use the package.

**Comment by adrianborkowski** [comment]
Sorry for asking here, but I'm newbie in Github.

Of course I can find link in that way, but I would like to get link just during adding image to Google Drive and add link to database in the same time. Is it possible? How can I contact You to ask some questions?

**Comment by torre76** [comment]
Hi @adrianborkowski,

First I want to tell you that I am sorry for being so annoying, but I am sick and tired about people who opens issues only because they had not read the docs.

Having said that, clearly you do not understand how [FileField](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.FileField) and [Storage](https://docs.djangoproject.com/en/1.10/ref/files/storage/#the-storage-class) class works in Django.

Basically, every time you use a **FileField** everything is managed by Django itself.
When you save a file, a unique identifier related to the **Storage** class is saved into your db (in this case I choose the _originalFilename_). 
With this data and using the _Storage_, Django can retrieve all the informations of the file you uploaded; **these informations are provided through the [File](https://docs.djangoproject.com/en/1.10/topics/files/#the-file-object) object**.

Basically, what you need to do is to follow this [simple example](https://docs.djangoproject.com/en/1.10/topics/files/#the-file-object) (the property - method you are looking for is _url_).

I strongly encourage you to study the underlying mechanism of Django, so you could also understand the code I wrote. The main purpose of OSS is to learn from others by looking at their code (and make it better, if it is possible).

Regards.
