### ISSUE TITLE
Using when offline (no internet)

### ISSUE THREAD

**Issue by yarnball** [torre76/django-googledrive-storage#24]
Hi,

Great work on this! Really good guide too.

I'd like to know how to use this repo when I don't have an internet connection.

Without an internet connection, it just tells me:

`ServerNotFoundError: Unable to find the server at accounts.google.com`

Is there a simple work around for this?

**Comment by torre76** [comment]
Hi @yarnball,

there is no workaround for this issue because this storage read and write to Google Drive _in real time_, without buffering on local hard disk.

Without internet connection it is impossible to reach Google Drive servers and write (or read) files.

If you want to debug locally simply use normal [Django File Storage implementation](https://docs.djangoproject.com/en/1.10/ref/files/storage/) which will save data on your local hard disk. Then, once you go on production, initialize the Google Drive Storage (surely on prod you will have internet connection).
