### ISSUE TITLE
Migrate to google-auth

### ISSUE THREAD

**Issue by thismatters** [torre76/django-googledrive-storage#45]
According to the [its docs](https://github.com/googleapis/oauth2client) `oauth2client` has been deprecated for a few years now and its replacement [google-auth](https://github.com/googleapis/google-auth-library-python) seems mature. Is there any plan to migrate?

**Comment by torre76** [comment]
Hi @thismatters,

this project was part of my path to become a Pythonic programmer a while ago.

While I am trying to maintain it, especially by releasing MR from users, I do not have plan to improve this project, basically because I have other interests right now.

If you want and if you have some spare time for this project, fell free to submit a PR, I gladly review it and, if it is working, I will surely upload to Pypi.

Regards

**Comment by aekanshd** [comment]
Yes, this is really slowing down my website. I did make a few local changes, but there seems to be errors. A little help would be nice.

**Comment by torre76** [comment]
Thanks to #49, this problem has been fixed.

New  [release 1.6.0](https://github.com/torre76/django-googledrive-storage/releases/tag/1.6.0), which has been [uploaded to PyPI](https://pypi.org/project/django-googledrive-storage/), has the fixes requested.
