### ISSUE TITLE
Development server starts with delay when gdstorage is used in multiple models.

### ISSUE THREAD

**Issue by Ruhshan** [torre76/django-googledrive-storage#46]
In my project, I've used gdstorage for 3 models. My models.py looks like this:

```
//models.py
from gdstorage.storage import GoogleDriveStorage

gd_storage = GoogleDriveStorage()

class Category(models.Model):
    name = models.CharField(max_length=100)
    category_image = models.ImageField(null=True, blank=True, storage=gd_storage)


class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(storage=gd_storage)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(storage=gd_storage)

```

When I'm running runserver, it's taking long time than usual to start. Sometimes getting socket connection error with googleapiclient package. I've noticed for each model __init__ method of GoogleDriveStorage class is executing, which is communicating with google and building a drive_service. 

Can there be a better way, like a singleton class which is reused by all the models? Or there is already a way that I'm missing?

Thanks in advance.

**Comment by torre76** [comment]
Hello @Ruhshan,

clearly the problem you have is related to your network system.  
Usually Google initialize itself in half of a second.

I do not have implemented a Singleton in this case by design. This way it is possible to assign different permissions at every model, if a Singleton is implemented, all models should have same permission.

Please check your connection and network and surely this problem will vanish.

Regards
