### ISSUE TITLE
Http 400 "Invalid Value"

### ISSUE THREAD

**Issue by pedrovgp** [torre76/django-googledrive-storage#59]
I configured everything as per the docs, but when I try to upload a picture through the UI, I get:
`<HttpError 400 when requesting https://www.googleapis.com/drive/v3/files?q=name...=json returned "Invalid Value". Details: "[{'message': 'Invalid Value', 'domain': 'global', 'reason': 'invalid', 'location': 'q', 'locationType': 'parameter'}]">`

Any hints?

**Comment by torre76** [comment]
This is a bug tracker for this project, not a programming school. 

This error is related to Google Drive API and there are a lot of causes for this. 

It is impossible to understand why you have this error without seeing what are you doing in your code. 

Since it is not a bug of this project, but likely an error on your code, you should check on help sites like StackOverflow, Google or even ChatGPT and not open an useless issue.

**Comment by pedrovgp** [comment]
You are right, sorry for that, I should have provided more details. To provide more info, it works without setting "GOOGLE_DRIVE_STORAGE_MEDIA_ROOT", but fails as stated if a provide one. You might leave this closed, I just wanted to inform.
